# This file was generated by GoReleaser. DO NOT EDIT.
cask "ingresso-finder-cli" do
  name "ingresso-finder-cli"
  desc "Use ingresso.com directly from the terminal"
  homepage "https://github.com/publi0/ingresso-finder-cli"
  version "1.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ingresso"

  on_macos do
    on_intel do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Darwin_x86_64.tar.gz"
      sha256 "37a4f1f0226d0a3d8e4b9c3b49e0bfedfe5b8c7e393a2cefd2c634992848bb8f"
    end
    on_arm do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Darwin_arm64.tar.gz"
      sha256 "ffb0b9227db07a32bbb44f541c6ddfc1d717a670c73fe560d15e44b6f2b0301c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Linux_x86_64.tar.gz"
      sha256 "c9ca52f71bb349f00f55ae57545f8c17c492d80f18ee15e35d27d1af0c973faa"
    end
    on_arm do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Linux_arm64.tar.gz"
      sha256 "76713b29a61153fe7237493eeb7bc34db81020e395a60abe795a3e5a0c05689e"
    end
  end

  # No zap stanza required
end
