# This file was generated by GoReleaser. DO NOT EDIT.
cask "ingresso-finder-cli" do
  name "ingresso-finder-cli"
  desc "Use ingresso.com directly from the terminal"
  homepage "https://github.com/publi0/ingresso-finder-cli"
  version "1.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ingresso"

  on_macos do
    on_intel do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Darwin_x86_64.tar.gz"
      sha256 "5dba0b95c6bd3f6909dc0ad026a3d8cad1edb25c2d507c956b37f35d45b0272b"
    end
    on_arm do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Darwin_arm64.tar.gz"
      sha256 "144edb70968c92f7f9fdcc1bb16e3c920c1ebb7e9b76f46863d3252dcbf31bec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Linux_x86_64.tar.gz"
      sha256 "061f2b8cff34c05e7f8e08f58415a13992f54703f71fe481438d64b00dbdc5d5"
    end
    on_arm do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Linux_arm64.tar.gz"
      sha256 "598db8b77ea8e606da0ecdf86cad2ed1237b4be71b347f7655d2a34a53bc7aa6"
    end
  end

  # No zap stanza required
end
