# This file was generated by GoReleaser. DO NOT EDIT.
cask "ingresso-finder-cli" do
  name "ingresso-finder-cli"
  desc "Use ingresso.com directly from the terminal"
  homepage "https://github.com/publi0/ingresso-finder-cli"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ingresso"

  on_macos do
    on_intel do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Darwin_x86_64.tar.gz"
      sha256 "49e00bf398ba7101f276c67f75796f74bc29ba18e289c7b910cdab1cdfa75fa0"
    end
    on_arm do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Darwin_arm64.tar.gz"
      sha256 "23fae865f1a5370c51a63f1ace31682ca928c3ceb03d07d3fd94272253eef391"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Linux_x86_64.tar.gz"
      sha256 "74b5b39d10b0e080d70bdd4cb28c9b87fe76909267acfaa2a788fee4e1c2bde3"
    end
    on_arm do
      url "https://github.com/publi0/ingresso-finder-cli/releases/download/v#{version}/ingresso-finder-cli_Linux_arm64.tar.gz"
      sha256 "e506d729aa571a1e3fa91eb5831c00dfa1049e1ff9dde984c6bdca3426546933"
    end
  end

  # No zap stanza required
end
